### ISSUE TITLE
Screen timeout does not respect video playback

### ISSUE THREAD

**Issue by BrandonDenisSmith** [pop-os/cosmic-idle#2]
As currently implemented, `cosmic-idle` will turn off the screen during active video playback. This is unexpected and undesirable.

Observed behavior: Absent active user input via keyboard/mouse/touchscreen, and after the `screen_off_time`, the screen turns off even if a video is playing in the foreground. I have observed this behavior with YouTube videos in Firefox (apt) and Chromium (flatpak). I have also observed it during playback with PlexDesktop (flatpak).

Expected behavior: As long as a playing video is visible on screen, the screen should remain on, regardless of user input or lack thereof.

I have not personally observed this, but I suspect that auto-suspend will also engage during video playback in the absence of user input. I will test that and update this issue with my observations.

**Comment by ids1024** [comment]
It should respect the idle inhibit Wayland protocol (https://wayland.app/protocols/idle-inhibit-unstable-v1), but I guess we need an implementation of the inhibit XDG portal as well (https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.impl.portal.Inhibit.html).

I think applications that support inhibiting suspend will use one or the other.

**Comment by ids1024** [comment]
There may be more that's needed to support idle inhibitors as used by different clients, but this should work now.
